#pragma config(Sensor, S1,     sn,             sensorLightActive)
#pragma config(Motor,  motorA,          ma,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		if (SensorValue(sn)>35) {
			playSound(soundBeepBeep);
			wait1Msec(1500);
			//playSound(soundBeepBeep);
			motor[motorA]=-20;
			wait1Msec(3000);
			//playSound(soundBeepBeep);
			motor[motorA]=-1;
			wait1Msec(10000);
			//playSound(soundBeepBeep);
			motor[motorA]=20;
			wait1Msec(2200);
			motor[motorA]=0;
			wait1Msec(800);
		}
		wait1Msec(500);
	}
}
