#pragma config(Sensor, S1,     one,            sensorEV3_Color)
#pragma config(Motor,  motorA,          a,             tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		if (SensorValue(one)>4) {
			setMotorSpeed(motorA, 40);
			wait1Msec(3000);
			setMotorSpeed(motorA, 0);
			wait1Msec(1000);
			setMotorSpeed(motorA, -20);
			wait1Msec(3000);
		}
		wait1Msec(100);
	}
}
